### ISSUE TITLE
Gwen ban not working

### ISSUE THREAD

**Issue by svenvv** [Monkey-Bubble/lol-pick-ban-ui#3]
A k'sante ban shows an empty slot on the ban screen.

**Comment by Cinzya** [comment]
Will need to use `champion.id` instead of `champion.name` here.

https://github.com/Monkey-Bubble/lol-pick-ban-ui/blob/b68cb90815d3eb7df9f9233a435c480a70dc782c/backend/state/converter.ts#L41-L43

**Comment by Cinzya** [comment]
18b93cf2c0c122327a4d7a593cd215463c398d87 and e48da4994112c54d7833b1ddd624e70a37219acb should fix this. 🙏
